// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkOfTpl2F1z1JTmPX0sLSUzLIhvG4gyAg',
    appId: '1:420768718928:android:9cb44655ac72cff5c1f155',
    messagingSenderId: '420768718928',
    projectId: 'finclever-cec82',
    storageBucket: 'finclever-cec82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHzU2QZQMD5VYlr99DhZiWXV6x2sjnN4s',
    appId: '1:420768718928:ios:a3c8e696103b277cc1f155',
    messagingSenderId: '420768718928',
    projectId: 'finclever-cec82',
    storageBucket: 'finclever-cec82.appspot.com',
    androidClientId: '420768718928-42s7lglc3dv9d2328ar7ve2hqr7nk7m5.apps.googleusercontent.com',
    iosClientId: '420768718928-vgv4o1r48q1473l2mh1ttclb5i3m3bvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.finclever',
  );
}
